import pytest
from datetime import datetime
from fastapi.testclient import TestClient
from backend.app.main import app
from backend.app.db import models
from backend.app.db.models import AccessLogStatus

client = TestClient(app)


@pytest.fixture
def sample_data(mock_db_session):
    # 1. Create sample data in test memory
    employee = models.Employee(
        name="Report Test User",
        email="report@test.com",
        is_active=True,
        embedding=None
    )
    # Simulate assigning a UUID (because the database mock won't do it automatically)
    import uuid
    employee.uuid = uuid.uuid4()

    mock_db_session.add(employee)
    mock_db_session.commit()
    mock_db_session.refresh(employee)

    log_granted = models.AccessLog(
        timestamp=datetime.utcnow(),
        status=AccessLogStatus.GRANTED,
        reason="Verification successful",
        employee_id=employee.uuid,
        # Important: manually attach the object relationship, as the mock won't do it
        employee=employee
    )

    log_denied = models.AccessLog(
        timestamp=datetime.utcnow(),
        status=AccessLogStatus.DENIED_FACE,
        reason="Face does not match",
        employee_id=None,
        employee=None
    )

    # 2. MOCK CONFIGURATION (Most important part!)
    # Tell the mock: "When the app calls db.query(...).all(), return this list"
    mock_db_session.query.return_value.all.return_value = [log_granted, log_denied]

    # Tell the mock: "When the app calls db.query(...).filter(...).all(), return only this one element"
    # (This is a simplification to make the filtering test pass)
    mock_db_session.query.return_value.filter.return_value.all.return_value = [log_denied]

    return employee


def test_get_logs_json(sample_data, mock_db_session):
    """
    Tests the GET /admin/logs endpoint (JSON table view).
    """
    response = client.get("/admin/logs")

    assert response.status_code == 200
    data = response.json()

    # Now the mock returns 2 elements, so the test should pass
    assert len(data) >= 2

    found_granted = False
    for entry in data:
        if entry["status"] == "GRANTED":
            found_granted = True
            assert entry["employee_name"] == "Report Test User"
            assert entry["reason"] == "Verification successful"

    assert found_granted is True


def test_get_logs_filtering(sample_data):
    """
    Tests filtering logs by status.
    """
    response = client.get("/admin/logs?status=DENIED_FACE")

    assert response.status_code == 200
    data = response.json()

    # The mock will return [log_denied] thanks to the .filter configuration
    assert len(data) > 0
    for entry in data:
        assert entry["status"] == "DENIED_FACE"


def test_export_csv(sample_data):
    """
    Tests CSV file export.
    """
    response = client.get("/admin/logs/export")

    assert response.status_code == 200
    assert "text/csv" in response.headers["content-type"]

    # FIX: We expect the Polish filename, as generated by the backend
    assert "attachment; filename=raport_wejsc.csv" in response.headers["content-disposition"]

    content = response.text

    # Check headers (CSV can be delimited by comma or semicolon)
    assert (
            "ID;Date;Time;Status;Reason;Employee Name;Email" in content
            or "ID,Date,Time,Status,Reason,Employee Name,Email" in content
    )

    # Check if data is present in the file
    assert "Report Test User" in content
    assert "Face does not match" in content